# Site Settings
title: Amoh's Resume
url: 'http://webjeda.com'
baseurl: '/cv' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: Justice Amoh
tagline: Machine Learning Researcher 
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'I am a Ph.D. candidate at the Thayer School of Engineering, Dartmouth College. My primary 
objective is to perform research in the field of electronics and machine learning with a focus
on using learning algorithms and signal processing tools to implement and investigate wearable
health monitoring devices for patients with lungs and airway diseases.'

#sidebar links
email: justiceamoh@gmail.com
phone: 660 273 0032
website: justiceamoh.github.io #do not add http://
linkedin: justiceamoh
github: justiceamoh
twitter: '@justiceamoh'
gscholar: https://scholar.google.com/citations?user=0iKKMSIAAAAJ&hl=en 

#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
